### PR TITLE
Circuit Nerf Two 

### PR DESCRIPTION
**Pull request by BrotherHangyul**
## About The Pull Request
Well. I warned you guys not to abuse them further. Aaaand people immediately took to abusing them even harder. Wow. I can't trust you guys to do anything.

The following modules are commented out to avoid further powergaming:
- Pull Module
- Throwing Module
- Syringe Module
- Cryo Module

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
balance: Circuits less powerful.
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Uncomment everything but grenade primer and the gun thing of weaponized.dm

**Comment by YellowKingThe** [comment]
Terrible change, revert the previous PR well you are at it.
This adds nothing and is just a salt PR by someone who doesn't even use circuits or attempt to understand them.
If you want to change circuits at least have someone who uses them be involved instead of just trying to make them useless.

**Comment by YellowKingThe** [comment]
If you think they should be removed entirely you are not the person that should be making these PRs alone.
You should take the time to learn something instead of just ripping it out entirely with no thought.

**Comment by YellowKingThe** [comment]
You think circuits at all are indicative of power gaming or rule breaking, a perfect example of why your circuit pr should be reverted and why this one should not be used. You are acting in bad faith in your prs.

**Comment by ErwinSnowden** [comment]
having used circuits to make flamethrowers, acid sprayers and atmos-deleters i think they need to go.

**Pull request closed without merging**
