### PR TITLE
Removing infinite money plants

### PR DESCRIPTION
**Pull request by Malerus**
## About The Pull Request
- Removing Golden Apple
- Removing Holy Melon

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
del: Removed Golden Apple and recipes tied to it, and Holy Melon which had gold in it
/:cl:

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
> this is just going to make people switch to other, slightly slower means of making infinite money

there are no other ways of making infinite money.

**Comment by Malerus** [comment]
> > this is just going to make people switch to other, slightly slower means of making infinite money
> 
> there are no other ways of making infinite money.

There is, this is just stopping the goofiest way of doing it

**Comment by Malerus** [comment]
> this is just going to make people switch to other, slightly slower means of making infinite money

We want them to do that :) 
They help us find out the issues to fix.

**Comment by biotear** [comment]
> > this is just going to make people switch to other, slightly slower means of making infinite money
> 
> We want them to do that :) They help us find out the issues to fix.

Then you should remove the trading point entirely. Because you're gonna be playing an eternal game of whack-a-mole.

**Comment by Hlscientist** [comment]
> > this is just going to make people switch to other, slightly slower means of making infinite money
> 
> there are no other ways of making infinite money.

watch me

**Pull request merged**
