### PR TITLE
Minor Knight Changes

### PR DESCRIPTION
**Pull request by shelteredfreak**
Just some quick minor changes to the Knight caste.

## About The Pull Request
This isn't anything major. Just some things I thought might be nice.

Gives the Knight-Captain a Thermic Lance melee loadout using the unused scout armor since I felt like all Knights should have a melee loadout. As well as replaces the Warden-Defender loadouts armor with the scout armor since I feel like it would be better, liable to change though. 

Also fixes the fact that none of the Knights had gunsmith knowledge since it was trying to apply a trait that in fact did NOT exist, now there is a innate list that contains the current contents of the gunsmith magazines 1 through 4 that acts as a replacement for the trait.

Also places the 4th gun magazine on the BoS armory bench.

ALSO fixes the gunsmith magazine giving the Trench Shotgun recipe, which was previously non-existant.

P.S. I copy pasted the scout armor code from the senior scout armor since the senior scout and basic scout share the same armor value. If someone wants to suggest better armor values for all of them, I'm open to suggestions, especially for the Knight-Captains.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Added a melee oriented Knight-Captain loadout with a Thermic Lance.
add: Adds in the unused Knight-Captain light armor for the new melee loadout, and replaces the Shotgun loadouts armor as well.
fix: Fixes the intended trait of all Knights having innate gunsmith knowledge.
balance: Places the 4th gun magazine on the BoS reloading bench.
fix: The 2nd gun magazine now gives you the Trench Shotgun recipe instead of attempting to give you the gun itself through knowledge.
/:cl:

### CODE REVIEW

**Comment by Legate-Maxson** [comment]
gun smith books?

**Comment by shelteredfreak** [comment]
> gun smith books?

the gun magazines

**Comment by ErwinSnowden** [comment]
G&B 5 is rare [almost impossibly so] because you could get full-auto tribeams and 128 damage plasma rifles with those energy weapon mods. Energy weapons are already in a good spot without those mods because they have a mostly superior firerate compared to ballistics. They have lower damage, yes, but most armor doesn't give much protection against lasers. They're also rechargeable (which admittedly doesn't count for much since you can get enough ammo to stock you for the whole round using a car's worth of salvage.)

I'd be more supportive if the energy weapon mods were split up and the ones like the Wattz Gigalens and Electro-shunt were put into G&B 5 while the others (Boosters, VATS module, Overdrive Chip) were in 3 and 4.

**Comment by shelteredfreak** [comment]
> G&B 5 is rare [almost impossibly so] because you could get full-auto tribeams and 128 damage plasma rifles with those energy weapon mods. Energy weapons are already in a good spot without those mods because they have a mostly superior firerate compared to ballistics. They have lower damage, yes, but most armor doesn't give much protection against lasers. They're also rechargeable (which admittedly doesn't count for much since you can get enough ammo to stock you for the whole round using a car's worth of salvage.)
> 
> I'd be more supportive if the energy weapon mods were split up and the ones like the Wattz Gigalens and Electro-shunt were put into G&B 5 while the others (Boosters, VATS module, Overdrive Chip) were in 3 and 4.

If it's going to be much of a problem, I'll just take it off of Knight-Captain and someone with more inclination with Balance handle that. I merely gave it to KC since literally no one in Brotherhood has access to energy mods despite energy guns being their main thing, which is painful.

**Pull request closed without merging**
