### PR TITLE
Circuit removal - V2

### PR DESCRIPTION
**Pull request by BrotherHangyul**
## About The Pull Request
'Advanced Data Theory' is now removed from the techweb, meaning circuits cannot be researched or printed.

I'm going to get a lot of flak for this, but in their current state, circuits are, simply put, bad for the game. They've been removed or reworked on almost every /TG/ codebase for a reason - they're stupidly powerful, and without counter. To count some of the things I've seen made using circuits:

- A virtually unkillable robot that can fire four wattz sniper rifles at once, cannot be killed with conventional gunfire and moves at lightspeed.
- Unmanned suicide drones that pose no risk to the user and will almost always kill their target.
- Automated crit-injectors.

None of these are fun to deal with. Nobody wakes up and thinks 'Hey, I just got killed with quite literally zero way to fight back or even remotely get out of the situation, that's fun!'. It's not fun for anyone but the user, and hell, they don't even make sense for the setting, nor were they ever intended to be in the game. Though I understand, see and like some of the more resourceful / funny parts of circuits, it's primarily used on the server as a method to powergame. If someone wants to port a circuit rework, go ahead, but right now they should be disabled.

V2 as I fucked up the other one.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
del: Removed circuitry from the RnD techweb and from the RnD in Eastwood / BOS, the only static spawns (to my knowledge.)
:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Lil Chud actually fixed his code.. even though removing the entirety of circuits instead of coding out the specific items that cause your little problems is a much worse option.. you still fixed yo code so congrats.

**Comment by TheCircuitsClown** [comment]
Well hello, mind telling, whats so fucking overpowered in circuits? Im just curious, how often you die from drone with four wattz2000 rifles, bomber drones and see dudes with autohealers?

Do you know that there is a single guy that knows how to make drones with several guns? This guy is me, and im playing like twice or once a fucking week, without killing a single guy, and you know whats more funny, drones cant aim in objects or people, they fucking shoot at X and Y, if your prone or in crit, it will never fucking shoot you even at point blank range.

Bomber drones? Do you know that they use something called "locator"? And that it cant see through fucking smoke? Yes you can quite litteraly fucking use a single smoke grenade and then EMP, and its whole story.

Oh about EMP. Even WEAKEST emp will 100% guarantee to disable any circuit in range, because it fucking burns wires and changes all value's in all modules.

Auto-injector circuits? Really? How often you seeing people with these? And did you know that auto-injector is more likely to kill you instead of killing you, because it fucking scans in cycle's, if your health wont will reach certain point it will keep healing utill OD and death, and if you, well, die, it will still pump all chems and get you corpse OD again.

Are you sure that circuits are "op" yet? Maybe, forging melee weapons that 2 hit people and parry fucking bullets, is far more balanced, and using fuck ton of drugs to become immortal too?

**Comment by TheCircuitsClown** [comment]
I've been doing circuits for fuck ton of time, and honestly, I see nothing overpowered, they are already barely fucking working, cameras broken, renamer modules having seizures, hyposprays drones cant interact with you, if you fucking c r a w l.

**Comment by TheCircuitsClown** [comment]
Yet, did I use my drones to wipe factions yet?
The only time, I did apply my drones for combat scenarious, was in fucking Wasteland server, after which I use these drones for EORG memes, or just improving existing shit.
Circuits take alot more preperations that a god damn EMP grenade, you know.
Circuits can always be parried. As I said, for drones with guns you can legit lay down and shoot drone if its MMI drone (I rarely use MMI ones.) or the drone operator that controlls them. 
Suicide bombers... Well, maybe, maybe its OP if your being chased by marathon runner with for example, a grenade that has two bluespace beakers of gunpowder, but still, smoke blinds drones, EMP fries them, and usually all drones have someone who controlls them, unless its MMI ofc.

> > I've been doing circuits for fuck ton of time, and honestly, I see nothing overpowered, they are already barely fucking working, cameras broken, renamer modules having seizures, hyposprays drones cant interact with you, if you fucking c r a w l.
> 
> > Well hello, mind telling, whats so fucking overpowered in circuits? Im just curious, how often you die from drone with four wattz2000 rifles, bomber drones and see dudes with autohealers?
> > Do you know that there is a single guy that knows how to make drones with several guns? This guy is me, and im playing like twice or once a fucking week, without killing a single guy, and you know whats more funny, drones cant aim in objects or people, they fucking shoot at X and Y, if your prone or in crit, it will never fucking shoot you even at point blank range.
> > Bomber drones? Do you know that they use something called "locator"? And that it cant see through fucking smoke? Yes you can quite litteraly fucking use a single smoke grenade and then EMP, and its whole story.
> > Oh about EMP. Even WEAKEST emp will 100% guarantee to disable any circuit in range, because it fucking burns wires and changes all value's in all modules.
> > Auto-injector circuits? Really? How often you seeing people with these? And did you know that auto-injector is more likely to kill you instead of healing you, because it fucking scans in cycle's, if your health wont will reach certain point it will keep healing utill OD and death, and if you, well, die, it will still pump all chems and get you corpse OD again.
> > Are you sure that circuits are "op" yet? Maybe, forging melee weapons that 2 hit people and parry fucking bullets, is far more balanced, and using fuck ton of drugs to become immortal too?
> 
> Yeah I'm uh. Pretty confident circuits are still bad. Melee can be countered by backpedalling, parrying bullets takes genuine skill. Smoke and EMPs need to be prepared in advance, most people don't carry them regularly - and that's all a suicide drone needs to kill someone. You, yourself, boasted about your robot-with-lasers being able to wipe entire factions solo. That's not balanced.

**Comment by TheCircuitsClown** [comment]
Circuits are a meme, and I love it. Its fun due to how much shit you can make from it, healing, logistics, power generators, atmos, drones, chemical manipulation, and hydroponics. For me circuits give alot of new possibilities and activities, as long as you understand how it works, I dont want circuits removed as a whole, just no :/

**Comment by ErwinSnowden** [comment]
Kimitus for the love of god please stop sockpuppeting yourself. This retarded strawman has gone on long enough. "TheCircusClown" isn't a real person, it's just an alt.

**Comment by BadAtThisGame302** [comment]
This is not a smart fella... he's a fart smella... removing circuits...

**Comment by HanSolo1519** [comment]
I'm against content removal and may be a bit biased as a circuit enjoyed, I do agree the murder robots are a bit lopsided in terms of balance.

Would be nice to neuter the throwing, gun circuits, etc, and leave the non-issue stuff such as drones that can see and talk, or voice-stuff. You can't really abuse a circuit that just relays what it sees.

**Comment by githubuser4141** [comment]
Eh.. why remove crit-injector robots? Softcrit was designed for FPS-TDM games like CoD or Battlefield, and doesn't belong in FO - it doesn't even make sense in the setting. A robot that injects you in crit isn't unbalanced because it's just QoL - prestimming without giving yourself a repetitive strain injury IRL.

Agree about the weaponized circuits, we should probably remove the components that throw items (or add a delay), remove the weapon mounts and add a delay to injectors/manipulators. IMO as long as it doesn't violate laws of physics (in the FO sense) it's not setting-breaking?

**Comment by TheCircuitsClown** [comment]
> Kimitus for the love of god please stop sockpuppeting yourself. This retarded strawman has gone on long enough. "TheCircusClown" isn't a real person, it's just your alt.

Who the fuck is a Kimitus bruh

**Comment by RonBag** [comment]
Please keep discussion on-topic or the comments will be locked.

**Comment by YellowKingThe** [comment]
How many people have actually be killed by any kind of circuit drone?
Also have you made an auto injector circuit? They are not that good and a rather big pain to deal with.
Circuits that auto inject are on the higher skill side of things, as for shooting drones, they have a bunch of built in restrictions with their parts, you would need to do some hacky stuff to make a single drone fire four wattz at once, and then you also need four wattz per drone, that is an expensive investment.
The autonomous explosion drone, if it actually kills you with no escalation is a problem but that is a rules problem, not a circuits exist problem, and is not really any different effectively then doing things like remote detonated grenades, or stacking landmines, or remote detonated duffel bombs, it just requires more setup, but also just throwing drones at people with no risk to yourself offensively is a violation of the escalation rules if I recall properly.
Overall this will just kill the one really open and creative outlets researchers have that isn't make murder chemicals, or murder robots, or other things, circuits have a gigantic area of application, for instance I have made pocket lights that illuminate a huge area, text to speech devices, slated to have a custom Circuit based radio created, and a number of other things that are possible that are not just murder bone.
If the things you are describing are uncounterable and zero risk then they need to be reported for power gaming.

**Comment by Al-1ce** [comment]
Personally, I think these should be removed simply because they don't really make sense or fit in the atmosphere.

Balance concerns aside, murder-drones are _generally_ not something I think people should have. And I can't think of anyone who would genuinely carry EMP grenades except the BoS.

**Comment by Hlscientist** [comment]
This man has never played with circuits 💀

**Comment by Hlscientist** [comment]
anyway, should be a rule thing, the only people who can actually make use of circuits are big brain autistic people with no time, just nerf some circuits like the movemnt, or decrease health for the chasis. I use circuits for auto harvesting plants

**Comment by githubuser4141** [comment]
> Personally, I think these should be removed simply because they don't really make sense or fit in the atmosphere.
> 
> Balance concerns aside, murder-drones are _generally_ not something I think people should have. And I can't think of anyone who would genuinely carry EMP grenades except the BoS.

Circuits do fit the atmosphere though, in FO it's a common theme to have "nerd scientists" invent or modify electronic devices? Like there's a ton of quests that involve fixing or sourcing components to someone's pet robot that acts as a carrier pigeon or a warning system or whatever. It's mostly just a sprite issue - the current circuits are styled to look like modern circuit kits you'd find at literally any geek store. If they were restyled to look like clunky 1980's tech it'd be fitting.

**Comment by BobNewman-max** [comment]
who farted?

**Comment by YellowKingThe** [comment]
> casually churn out pre-war technology pieces or robots. I don't recall the time in any fallout game in which an NPC created a homing suicide drone that appears out of nowhere and cannot be shot at and then uses it to kill you, instantly. Nor do I recall the time an NPC created a virtually unkillable murderbot that can fire four weapons at the same time, move across your screen at lightspeed and is impervious to all fire.

I think you just described the Institute.

**Comment by githubuser4141** [comment]
> 

That's why I said "remove gun circuits, add a delay to injector circuits, blacklist explosive chems, etc etc." You must've not read the part where I said that such things break the physics of FO and shouldn't exist.

**Comment by githubuser4141** [comment]
> > > 
> > 
> > 
> > That's why I said "remove gun circuits, add a delay to injector circuits, blacklist explosive chems, etc etc." You must've not read the part where I said that such things break the physics of FO and shouldn't exist. Circuits shouldn't be removed in their entirety, they should be nerfed until you can't make superweapons out of them anymore. A circuit that auto-injects someone, or activates a beacon when it detects they haven't moved for a set amount of time (example) fits in universe, in my opinion.
> 
> That's your opinion, and whilst I respect it, I have my own. No common wastrel researcher in _Yuma_ is going to be able to develop tech like that. Nobody here is a protagonist, nobody here is a main story character, we're all common NPCs at best. If you'd like to code an alternative, I actively encourage you to do so - however, I think this is the best route we can take if we want to make the server more immersive and less SS13-y.

Circuit tech.. can't be made by wasters, yeah, only BoS/Vault can manufacture them. If you're removing them from RnD perhaps BoS/Vault could spawn with a upgraded printer? This prevents them from willy-nilly handing the printers out to just about everyone (like they do.)

**Comment by YellowKingThe** [comment]
> > > 
> > 
> > 
> > That's why I said "remove gun circuits, add a delay to injector circuits, blacklist explosive chems, etc etc." You must've not read the part where I said that such things break the physics of FO and shouldn't exist. Circuits shouldn't be removed in their entirety, they should be nerfed until you can't make superweapons out of them anymore. A circuit that auto-injects someone, or activates a beacon when it detects they haven't moved for a set amount of time (example) fits in universe, in my opinion.
> 
> That's your opinion, and whilst I respect it, I have my own. No common wastrel researcher in _Yuma_ is going to be able to develop tech like that. Nobody here is a protagonist, nobody here is a main story character, we're all common NPCs at best. If you'd like to code an alternative, I actively encourage you to do so - however, I think this is the best route we can take if we want to make the server more immersive and less SS13-y.

Is this for balance or immersion? You said it was a balance issue, now it is immersion?
There are also literally npcs that build and repair robots by salvaging them in lore.
Also if you are so big about the lore of the server, then why are you calling it -Yuma- it isn't -Yuma- that is just a placeholder it takes place in the -Mohave-.
This is just a bad arguement for why we should implement it at the end of the day.
Sure remove broken stuff or you know punish people that make op shit for power gaming.
Don't just remove a massive feature of what RnD can do beyond stare at a screen and make mechs without a replacement in the same vein however.

**Comment by TheCircuitsClown** [comment]
Bro. Do you know why everyone who used or uses circuits, are againist this "temporary" disable of circuits?
Because nobody will fucking fix this shit, I seen dozens of servers that "temporary" disabled them and nobody ever tried to fix it, because its difficult they say. Instead everyone embraced "new TG circuits", they dont even have fucking text to speech or screens, the basic fucking modules.. If you want to fix circuit then temporary disable certain modules, like grenade primer circuit, not the whole fucking thing.

**Comment by Legate-Maxson** [comment]
Due to community outpour this PR is being closed sorry.

**Pull request closed without merging**
