### PR TITLE
role balances and changes

### PR DESCRIPTION
**Pull request by BobNewman-max**
Changes their roles e.c.t, read the PR

## About The Pull Request
Fucks with the BoS roles, fewer lower roles, more paladin roles, better gear. I won't fuck with the PA nerf as that isn't my area but I'll gladly fuck with their loadouts that are currently min-maxed with the setup of either shit or amazing.

HP had a commented out loadout with a gauss rifle, just remove the gauss rifle. EZ. Done.

SPs Had sub-par rifles that didn't really make them scary, now they are.

Ps still have their AER9s which are shit but I'm not going to buff them too much.

HK Now gets a DKS sniper instead of a wattz2k (wasn't even a 2Ke) so their loadout actually makes you think on what to choose. Was going to change their shotgun but fuck it, some people like it for some reason.

SK now gets a lever action instead of a browning auto. some will say its a buff, some will say its a nerf. Argue as you will.

Knights no longer get their rippers with shields, its now the shishkebab. They now have to choose, ranged AER9 that is shit or melee that is taking their backpack slot. 

HS now gets a glock86 instead of a wattz1k because I love faction head role having a pea shooter. So lets change it to them getting a scary pistol (don't hand it away instantly or I'll gib you upon doing so.)

Senior Scribes get an AEP7 now and their research loadout is actually worth picking now. Because only 2 papers for research is GOOD but not amazing. Now with the senior being 1 slot, they can choose. Speedrun research or speedrun medical. Up to them. I don't care.

Scribes get an AEP7 now instead of a wattz 1k because the wattz1k is funny and people keep saying they hate it. So now go hate the AEP7. Cool.

Initiates have no major/minor changes apart from slots.

Slot changes:

HK = 1
HP = 1
HS = 1

SK = 1 (was 2)
SS = 1 (was 2)
SP = 1 

K = 3
S = 2 (was 3)
P = 2 (was 1)

Initiate = 4 (Was 3)

Off-duty = 0 (they're broken. When they're fixed re-enable them please.)

Now the BoS have less in numbers and have more balance. People kept saying scribes do nothing well, now they can do something. Same goes for the knights and paladins. Now your loadouts are better because people keep telling me BoS is either terrible or amazing. So here, this is the solution. 

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
balance
/:cl:

### CODE REVIEW

**Comment by ZAB909** [comment]
More paladins isn't needed and why do you need to lower initiate role and seniors? 

Should remove all the slot changes from this PR and atomise it

**Comment by BadAtThisGame302** [comment]
I don't like the slot changes, these ones were better https://github.com/AtomBombf13/AtomBomb/pull/227 in my opinion ~~(except for the Elder)~~ The equipment changes seem fine mostly, probably should look about the DSK and shishkebab being changed/stat rebalanced though.

**Comment by Weaselburg** [comment]
#299  is better imo because reducing slots for knights that much and adding paladins is not going to make the faction better - though i might get proven wrong. the weirdest thing, though, is reducing Initiate slots. they're initiates, come on.

also, like i said in #299 , adding the hunting rifle to head knight changes nothing since they can already craft it.

**Comment by companoo** [comment]
dont add paladins

**Comment by YellowKingThe** [comment]
> Every combat role in the Brotherhood essentially gets combat armor right now, so their weaker weapons are more than made up for in protection

Scout Knight Armor is worse then legion recruit armor.

**Review by RonBag — APPROVED** [review]

**Pull request merged**
