### PR TITLE
Disables weather for now

### PR DESCRIPTION
**Pull request by RonBag**
## About The Pull Request
Disables weather until we can fix the multiple problems with it. Currently the sounds don't work, the weather effects itself is too buggy, and the weather doesn't really add much to the game. This will be here until I can finish my fix for it.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
Weather can add a lot to the game, at least for the atmosphere. I feel like if this were to be disabled, it'd be swept under the rug and never touched again.

**Comment by RonBag** [comment]
> Weather can add a lot to the game, at least for the atmosphere. I feel like if this were to be disabled, it'd be swept under the rug and never touched again.

We're going to the old system

**Comment by out-of-phaze** [comment]
the sounds were fixed on sunset like two months ago, they're just awful sounds

**Comment by RonBag** [comment]
> the sounds were fixed on sunset like two months ago, they're just awful sounds

thanks

**Pull request merged**
