### PR TITLE
Removes security vests from Eastwood armory, and buffs heavy bulletproof vest

### PR DESCRIPTION
**Pull request by RonBag**
## About The Pull Request
The vests in the Eastwood armory are a straight upgrade to their loadout, so this removes them.

Additionally, buffs the heavy bulletproof vest because it's worse than the light one.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by DeltaDav** [comment]
Replace those armor with basic eastwood security armor instead of a plain removal.

**Comment by RonBag** [comment]
> Replace those armor with basic eastwood security armor instead of a plain removal.

Why do they need that? They spawn with it and no other faction spawns with extra armor unless I’m mistaken.

**Comment by DeltaDav** [comment]
Doesnt the BoS have spare initiate equipement ?
Also, town isnt a military faction, and work as a militia. It would make sense to have some spare armor in case of emergency, to give too other town officials and some citizens.

**Comment by RonBag** [comment]
> Doesnt the BoS have spare initiate equipement ? Also, town isnt a military faction, and work as a militia. It would make sense to have some spare armor in case of emergency, to give too other town officials and some citizens.

I'll give them some light security vests and helmets.

**Pull request merged**
