### PR TITLE
Revert "Revert "Faction currency re-enabled, money buff, vending prices adjusted, added money printers to map""

### PR DESCRIPTION
**Pull request by ErwinSnowden**
Reverts AtomBombf13/AtomBomb#474

This was not a bad change, it just needed adjustments. Also holy shit can we please get test-merges for things like this?

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Me when the uuuh... the.... TGS... is... erm... the...

**Comment by RonBag** [comment]
> Reverts #474
> 
> This was not a bad change, it just needed adjustments. Also holy shit can we please get test-merges for things like this?

It was test merged in the only way I can. Anyways... We agreed that it wasn't bad and just needed some adjustments and Yonsi is working on them

**Comment by CaputCapital** [comment]
The faction currency PR is not a bad PR as it reintroduces faction-specific currencies, but I also agree that it can use some adjustments. USDs could use a higher maximum stack limit as there comes the risk of accidentally losing excess cash in your caps pouch if you stack over the maximum limit allowed for USDs. This is a bug which can be replicated with ores in a mining pouch,

Having every vendor on the map require only payments in USDs may not be the best idea. Here are some suggestions:

Most vendors throughout the wasteland, outside of Eastwood (excluding the attachments and wasteland guide vendors) should require USDs. Vendors in specific? The medical vendors, engineering vendors, RobCo vendors, the vendor which sells the Dean's Electronics book, and BOS vendors. If it's a vendor that would reasonably take USDs, it's fair game. Some vendors such as the attachments, wasteland guide, crafting vendor, and weapon parts vendor can take caps.

Vendors inside of the NCR base should require NCR dollars for purchases.

Vendors inside of Eastwood can either require USDs or just caps for purchases.

Legion doesn't have any vendors inside of their camp to which denari and aurei can see use. Therefore, Legion may have to exchange their currency in Eastwood.

If these suggestions are adopted in part or all, feedback is required. There is a chance that this may or may not go over well with most players.

**Comment by ErwinSnowden** [comment]
> The faction currency PR *snip*

Personally I think USD should be used for SS13 vending machines but the protectrons should use caps.

Since Yuma is Legion territory, exclusively "NCR dollar" vending machines seems out of character because they wouldn't be able to maintain or set these up... It also invalidates the NCR dollar being a fiat currency that is useless since it can actually purchase material goods? An NCR subtype for vending machines seems like bloat.

I do want the change to stay in.

**Comment by CaputCapital** [comment]
I agree with protectrons taking caps.

The change should stay in.

**Pull request closed without merging**
