### PR TITLE
lore-accurate rangemaster + low-tier plasma pistol

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request

colt rangemaster is now chambered in .223/5,56 as per FO1/2
brought down from high-tier down to mid/low tier due to reduction in power
replaces service rifle in random spawn locations, we do not need multiple semi-auto 5.56 rifles
service rifle remains in NCR service

stats:
27 damage, 10rnds
rate of fire remains identical

adds the short plasma gun
uses plasma cans instead of batteries
a safe alternative to the plasmusket
only deals 30 damage, same as a 10mm pistol, and has the slow plasma projectile but is resisted by few armors
also fires more slowly than any pistol
and has an astonishing magazine size of 27, though finding enough plasmacans to fuel it may be hard

inspired by the FO4 plasma gun: plasf13

plasmusket and plasma gun now both use a projectile for ghetto plasma weapons, plasma caster projectile will be the OP one
## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
why delete the plasmacaster projectile?

**Comment by cornercube** [comment]
> why delete the plasmacaster projectile?

its just being renamed so it wont be confused for whatever the P94 plasma caster will use when its added
since someone is making a sprite for it to replace the old ugly one

**Comment by Weaselburg** [comment]
30 for the magazine might be a bit much, given how easily you could throw a few attachments on it to make it much higher damage, which isn't helped by the fact that plasma is barely resisted by anything.

plus, I think the attachments that increase energy weapon damage won't actually decrease ammunition count, because it uses cans.

**Comment by cornercube** [comment]
> 30 for the magazine might be a bit much, given how easily you could throw a few attachments on it to make it much higher damage, which isn't helped by the fact that plasma is barely resisted by anything.
> 
> plus, I think the attachments that increase energy weapon damage won't actually decrease ammunition count, because it uses cans.
clip size reduced to 27 and fire delay increased from 4 to 5 to reduce spam potential

**Comment by ErwinSnowden** [comment]
> plus, I think the attachments that increase energy weapon damage won't actually decrease ammunition count, because it uses cans.

it wouldn't take energy weapon attachments period because it's a ballistic subtype, like the lasmusket.

**Pull request merged**
