### PR TITLE
Reverts "Jaapnese"

### PR DESCRIPTION
**Pull request by ErwinSnowden**
Reverts AtomBombf13/AtomBomb#434

Grievous lore-break. Japan doesn't exist in the fallout universe, so the language fits in as well as the "schoolgirl uniforms" at the costume shops do.

### CODE REVIEW

**Comment by RonBag** [comment]
Japan is a sovereign island nation in East Asia located in the Pacific Ocean. It is made up of four main islands (Honshu, Hokkaido, Kyushu and Shikoku) and thousands of smaller islands. Japan has a long and rich history, culture, and is known for its contributions to technology, industry, and cuisine. It is home to a population of over 126 million people and is governed as a constitutional monarchy with a parliamentary government.

As for the pull request to remove it, the reason it will not be merged is that the existence of Japan is a historical and geopolitical fact that is widely recognized and accepted by the international community. Such a pull request would be considered inaccurate, nonsensical, or trolling. It's unlikely it would be given a serious consideration and would be closed.

**Comment by RonBag** [comment]
Sorry, Vega. The robots have spoken.

**Comment by ErwinSnowden** [comment]
> Sorry, Vega. The robots have spoken.

OBJECTION! IT WAS MERGED UNDER A CODE OPTIMIZATION/REFACTOR. THIS OBVIOUSLY WAS NOT THE CASE, MEANING IT WAS MERGED UNDER FALSE PRETENSES!

**Comment by companoo** [comment]
renames it while keeping all the verbs japanese

also japan still exists

must be a troll

**Comment by BadAtThisGame302** [comment]
https://fallout.fandom.com/wiki/Japan

Wake up Joe... a High School planned to take a trip to Japan before the War.

**Pull request closed without merging**
