### PR TITLE
removes mechs lol

### PR DESCRIPTION
**Pull request by BrotherHangyul**
## About The Pull Request
Yeah.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
del: Mechs can no longer be researched.
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Brotha mad he died to a mech, ban this user from the GitHub.

**Comment by K4rlox** [comment]
ided removal
absolute skill issue

**Comment by Al-1ce** [comment]
A good change. +1

**Comment by Al-1ce** [comment]
Research as a whole should be zapped but that's just my two cents.

**Comment by githubuser4141** [comment]
Sad, I spent some time trying to improve them but looks like that's a waste of time with how many upboats this has. :(

**Pull request merged**
