### PR TITLE
Faction currency re-enabled, money buff, vending prices adjusted, added money printers to map

### PR DESCRIPTION
**Pull request by Malerus**
## About The Pull Request
- Added faction money printers
- Made vending machines only accept USD
- Added USD to trashloot table
- Adjusted vending machine prices to be less brutal
- Add money printers into the map (NCR and USD printers are in Eastwood, Legion printer is in Legion camp)

image

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Re-enabled faction currencies
add: Faction money printers
tweak: tweaked a few things
balance: rebalanced money value tiers
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
What's the point of ncrpay_veteran for example, is it used for the money stashed of certain NCR or what

**Comment by Malerus** [comment]
> What's the point of ncrpay_veteran for example, is it used for the money stashed of certain NCR or what

it seems to be a var for to set up another way of defining f13cash to be generated. Right now all Rangers are under  f13cash/random/ncr which streamlines them all to be the same, however, that can always be separated and controlled through ncrpay if needed. Currently it's unused.

**Comment by BadAtThisGame302** [comment]
> > What's the point of ncrpay_veteran for example, is it used for the money stashed of certain NCR or what
> 
> 
> 
> it seems to be a var for to set up another way of defining f13cash to be generated. Right now all Rangers are under  f13cash/random/ncr which streamlines them all to be the same, however, that can always be separated and controlled through ncrpay if needed. Currently it's unused.

Will you use it for the NCR/Legion pay, will you keep it, remove it?

**Comment by Malerus** [comment]
> > > What's the point of ncrpay_veteran for example, is it used for the money stashed of certain NCR or what
> > 
> > 
> > it seems to be a var for to set up another way of defining f13cash to be generated. Right now all Rangers are under  f13cash/random/ncr which streamlines them all to be the same, however, that can always be separated and controlled through ncrpay if needed. Currently it's unused.
> 
> Will you use it for the NCR/Legion pay, will you keep it, remove it?

I'm just leaving it alone for now, it's not effecting anything.

**Comment by Al-1ce** [comment]
> Will you use it for the NCR/Legion pay, will you keep it, remove it?

I think later down the line, adding a system of ATMs for the NCR and maybe a sort of mailing outpost for the legion allows the two major factions and their soldiers to receive pay in regards to their position, or maybe even how well they've been doing in some sort of event or raid. 

Possibly an easier (and setting-friendly) means to supply aid whenever it's viewed as earned and what-not. Food for thought.

**Pull request merged**
