### PR TITLE
Comments out SR (Strange Reagent)

### PR DESCRIPTION
**Pull request by BrotherHangyul**
## About The Pull Request
Entire point of the decay PR was to make revival not possible after 15 minutes, some leeway can be given when a creative solution is thought of, eg: bodyswapping, cyborgs. SR is not creative and completely flips the intent of body decay. Strange Reagent is now disabled and cannot be made.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
del: Strange Reagent commented out.
:cl:

### CODE REVIEW

**Comment by Bluebento** [comment]
SPEEDMERGE!!!!

**Comment by ErwinSnowden** [comment]
Begin again.

**Comment by RonBag** [comment]
Thanks, this was intended to be removed but I forgot

**Review by RonBag — APPROVED** [review]

**Comment by BadAtThisGame302** [comment]
How about you code something for everything you remove challenge (Impossible, will never be done)

**Comment by Hlscientist** [comment]
fix SYNTHFLESH!!

**Comment by CaputCapital** [comment]
SR is "not creative" and "completely flips the intent of body decay"

We're bound to find catatonic bodies turning up in clinics more often, guaranteed. I've seen it done on Bad Deathclaw as I've seen it on previous iterations of FO13. Then it becomes the next "not creative" concept that "completely flips the intent of body decay" which is either heavily moderated upon under clauses of "powergaming" or prevented through coding. 

The "creative solution" of a brain in an MMI, to be inserted into a mech or to be held is just another fancy way of circumventing death permanence. But why the need for a brain to put into a cyborg or mech when you have positron brains?

The push for death permanence is being encouraged by the community manager and coders. I hate to say it, but I'm slowly finding myself against this hard stance on death permanence with more PRs being merged to reinforce this concept in what appears to be "death insurance" scheme.

**The reasons why I'm against this idea of death permanence:**
1. A faction member decides to hide the body of an opposing faction member in an obscure place after looting them. That opposing faction member's body decays despite everyone in their faction looking everywhere for them.
2. SR getting axed just for death insurance. SR became a rarity to put together after holy melons got their reagents changed, now SR is removed it's just more death insurance.
3. The preacher's importance is made even more meaningless. There is no connection to be formed or cooperation to take place between the preacher and clinic to revive a decayed corpse quicker. SR is axed from code and the reagents in holy melons have been already screwed with to prevent access to holy water.
4. Decay and SR removal was never taken away during the start of Atom Bomb to begin with. Players not liking death permanence partially comes from the fact that they are forced to respawn or wait until the next round. The previous PRs in favor of death permanence already guarantees a likely restart vote at the 2:30 mark. I have to mention that most players don't like it when a core element is taken from them and it's been proven in previous iterations of FO13. I have reason to believe that population is going to decrease significantly due to these PRs.
5. Half of the players end up leaving the game anyway after they die. Trying to revive them doesn't work because they're ghosted and disconnected.
6. Most people don't want to look for other alternatives. (unless somebody sees this and challenges this through proving me wrong, by all means go ahead) My point is that you can't force change in the same way you couldn't change unexperienced NCR/Veteran Rangers easily getting ganked by Legion unless those NCR had experienced players backing them up.
7. If you want to put in body decay to make reviving bodies more complicated after sitting out long enough, people will have problems no doubt. I will say that it can be mitigated with moderation and by moderation, I mean not adding a load of PRs just to prevent people from being revived after their body decays. **HIScientist has a point with pushing for synthtissue to get fixed.** 
8. Round-ending sucks and most people are going to agree with this. Even if active MMIs being placed in borgs and mechs becomes the main ploy to circumvent death permanence, how "creative" will it become then?

**Comment by ErwinSnowden** [comment]
> We're bound to find catatonic bodies turning up in clinics more often, guaranteed. I've seen it done on Bad Deathclaw as I've seen it on previous iterations of FO13. Then it becomes the next "not creative" concept that "completely flips the intent of body decay" which is either heavily moderated upon under clauses of "powergaming" or prevented through coding.
> 
> *snip*

This sounds like it was written by someone obsessed with winning, but yes: seeing more cyborgs would be fun because they're weaker than humans. Death isn't the end, but it still is a penalty.

**Pull request closed without merging**
