### PR TITLE
Eastwood map re-upload because branch borked

### PR DESCRIPTION
**Pull request by Malerus**
### About The Pull Request
- Remapped where the clinic would be
- Expanded the kitchen and gave them a roof botany area
- Replaced shutters with blast doors
- Gave the main operating area of the clinic full town access
- Gave the basement of the clinic an ammo bench
- Created new access for Mayor, Researcher, and Town Doctor
- Removed overlapping accesses that other factions had with the town
- Gave Great Khans their own access node for airlocks
- Removed the RnD console from the hospital dungeon
- Added more blank space for hobotents
- Gave Prospector an ORM
- Fixed the jukebox and put it in the bar
- Removed a modded high-tier BP from the hospital dungeon
- Changed the PA Deathclaw dungeon timer from 30 minutes to 60
- Adjusted the PA Deathclaw dungeon to not be easily cheesed by long-range lasers.
- Added security record terminals to Eastwood
- Updated the Den basement to have an ammo bench, metalworking bench, autolathe, chem storage, workbench, photo copier, and a bottler.
- Rearranged the Den basement 

These were all requests from the players and staff. I personally wanted to fix the Great Khan access issue because it wasn't handled correctly.

Main:
image

Lower:
image

image

Upper:
image

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Created new access for Mayor, Researcher, and Town Doctor
add: Gave Great Khans there own access node for airlocks
del: Removed overlapping accesses that other factions had with town
tweak: Remapped where the clinic would be and expanded the kitchen
/:cl:

### CODE REVIEW

**Comment by cornercube** [comment]
link to #187 so it can close that issue

**Comment by Malerus** [comment]
Issues fixed in https://github.com/AtomBombf13/AtomBomb/issues/193#issue-1456620868 and https://github.com/AtomBombf13/AtomBomb/issues/187

**Comment by ErwinSnowden** [comment]
Since this already touches the hospital, please consider replacing/removing the "/obj/effect/spawner/lootdrop/f13/blueprintVHighPartsWeighted" in the hospital's basement for something more befitting such an easy ruin. Currently its just a free LMG, AMR or Rangemaster blueprint... stacked on top of a mid-tier one.

Also because this already touches the lower Z, would it be possible to make the power armored deathclaw bunker open at one hour instead of 30 minutes?

**Comment by Malerus** [comment]
> Since this already touches the hospital, please consider replacing/removing the "/obj/effect/spawner/lootdrop/f13/blueprintVHighPartsWeighted" in the hospital's basement for something more befitting such an easy ruin. Currently its just a free LMG, AMR or Rangemaster blueprint... stacked on top of a mid-tier one.
> 
> Also because this already touches the lower Z, would it be possible to make the power armored deathclaw bunker open at one hour instead of 30 minutes?

image

image


Done

**Pull request merged**
