### PR TITLE
Various bug fixes

### PR DESCRIPTION
**Pull request by RonBag**
## About The Pull Request
- Makes wounds GC properly (Thanks out_of_phaze)
- Removes ballistic spawns from digging up sand that were causing GC errors (It didn't work properly anyways, so this is not removing loot spawns)
- Removed outdated linemelee leftover
- Fixes quirk loss runtimes
- Fixes medibeam going invisible when wielded
- Fixes used steady sprite
- Fixes unspawnable gang items
- Fixes climbing out of water spam
- Fixed anvil template being placed on map
- Fixed two loadout items for Eastwood

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by out-of-phaze** [comment]
I fixed the spawners properly on Sunset as well. https://github.com/sunset-wasteland/sunset-wasteland/pull/308

**Comment by RonBag** [comment]
> I fixed the spawners properly on Sunset as well. This also increases performance by only selecting a type on turf init, and spawning that type only when you pick it up. Would absolutely recommend grabbing it. [sunset-wasteland/sunset-wasteland#308](https://github.com/sunset-wasteland/sunset-wasteland/pull/308)

Oh nice, thank you. I'll include that in this, then.

**Comment by out-of-phaze** [comment]
lol guess not

**Comment by RonBag** [comment]
> lol guess not

next pr now…

**Pull request merged**
