### PR TITLE
Updated robot access to BoS

### PR DESCRIPTION
**Pull request by Malerus**
We're moving away from SS13 access setups

## About The Pull Request
- Updated robot access to BoS access
- Minor map fixes

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: tweaked accesses for robots
fix: fixed a spawener misplacement
/:cl:

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
this might as well be a removal PR considering the BoS don't use robots and they certainly never ever use AIs 😄 stealth town nerfs

**Comment by Malerus** [comment]
> this might as well be a removal PR considering the BoS don't use robots and they certainly never ever use AIs 😄 stealth town nerfs

Staff request

**Comment by ErwinSnowden** [comment]
my issue with it is that it prevents anybody but the BoS from using things like posibrains when anybody with an R&D set should be able to use cyborgs

**Comment by Malerus** [comment]
> my issue with it is that it prevents anybody but the BoS from using things like posibrains when anybody with an R&D set should be able to use cyborgs
They still can. It's always been the same.

**Pull request closed without merging**
