### PR TITLE
Bye sleep healing

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request
Being in soft crit, pressing sleep button and healing to stand right back up in the dungeony you're looting and continuing to raid it with such cheese

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
del: Removed sleep healing
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
This makes belowground mining a lot tougher, why not adjust dungeon mobs so they'd attack in crit?  Otherwise you can get around this with implants.

**Comment by Al-1ce** [comment]
> This makes belowground mining a lot tougher, why not adjust dungeon mobs so they'd attack in crit?  Otherwise you can get around this with implants.

The vast, vast majoriety of wastelanders are not going to have implants.

As for the PRs sake, I think sleeping _should_ still heal, so-long as the user is in a bed. Fixes the cheese and leaves the mechanic to exist in a way that makes sense.

**Comment by YellowKingThe** [comment]
If you are going to do this you might as well remove sleeping entirely, if you can't heal from it it serves no purpose other then to be a trap option for people not familiar with the change.
Honestly sleep healing should be left in in my opinion due to the husk timer, making pve high lethality isn't going to help the server in my opinion.

**Comment by CaputCapital** [comment]
The issue I have with this is that in the event of someone getting disconnected in a dungeon for any reason and they reconnect back in crit, they're basically screwed.

If healing in sleep is getting removed, then the fast metabolism rates of stimpaks, super stimpaks, healing powder, healing poultice, and bitter drink while at full health should be removed.

**Comment by Legate-Maxson** [comment]
we are going to add execute for mobs

**Pull request closed without merging**
