### PR TITLE
Removes Ranger Takedown.

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request
It currently ignores the STUNIMMUNE flag, stun combat isn't generally fun and honestly I can't be bothered to recode it to abide to standard stun parameters.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
del: The library of Bearlexandria was burnt to the ground, with it the knowledge of the Ranger Takedown was lost.
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Nope.

**Comment by ErwinSnowden** [comment]
> Nope.

What a measured response, surely this man truly believes that being able to disarm anyone instantly and taking their gun to be balanced and fun for all parties involved.

**Comment by BadAtThisGame302** [comment]
> > Nope.
> 
> 
> 
> What a measured response, surely this man truly believes that being able to disarm anyone instantly and taking their gun to be balanced and fun for all parties involved.

Okay remove berserker rites too then or keep ranger takedown bud.

**Comment by ErwinSnowden** [comment]
Berserker rites are an optional CQC loadout that completely prevents you from using guns, the Ranger Takedown has no downside. It's a net positive to Rangers if they know how to use it, while Berserker rites with all the unarmed nerfs is essentially a sidegrade.

I won't be removing it because it is mainly a damage dealing technique and not a reskinned innate SS13 stunbaton.

**Comment by CaputCapital** [comment]
> > Nope.
> 
> What a measured response, surely this man truly believes that being able to disarm anyone instantly and taking their gun to be balanced and fun for all parties involved.

Sounds like this coder got ranger takedown'd and now wants it PR'd out of the game. Ever heard of right clicking yourself with help intent while in combat mode? It's surprisingly effective for being able to recuperate from a ranger takedown. Anybody can do it.

**Comment by ErwinSnowden** [comment]
> Sounds like this coder got ranger takedown'd and now wants it PR'd out of the game. Ever heard of right clicking yourself with help intent while in combat mode? It's surprisingly effective for being able to recuperate from a ranger takedown. Anybody can do it.
> 
> Imagine if a coder made a push to remove bolas just because "having your movement speed capped isn't generally fun" when you can just toggled throw on and catch the bola.

Off-topic discussion will not be tolerated, make some actual criticisms rather than insulting the author of this PR.

**Comment by Al-1ce** [comment]
> Sounds like this coder got ranger takedown'd and now wants it PR'd out of the game. Ever heard of right clicking yourself with help intent while in combat mode? It's surprisingly effective for being able to recuperate from a ranger takedown. Anybody can do it.


That isn't a solution to the issue. 

 
>Anybody can do it


Not everyone who plays this server is familiar with TG-style combat mechanics. A fair amount of our player base (myself included) doesn't even play with right-click speciality functionality on. 

That aside - Ranger Takedown isn't something you'd normally run into while in a brawl. It's too powerful in it's current state to exist without any drawbacks whatsoever.


> Imagine if a coder made a push to remove bolas just because "having your movement speed capped isn't generally fun" when you can just toggled throw on and catch the bola.


Context matters. Bola's function quite a bit different to an instant disarm/knockdown ability.

I suppose I should note that most players aren't insanely paranoid and do not have throw selected in the event someone _MIGHT_ bola them.

**Comment by CaputCapital** [comment]
> > Sounds like this coder got ranger takedown'd and now wants it PR'd out of the game. Ever heard of right clicking yourself with help intent while in combat mode? It's surprisingly effective for being able to recuperate from a ranger takedown. Anybody can do it.
> > Imagine if a coder made a push to remove bolas just because "having your movement speed capped isn't generally fun" when you can just toggled throw on and catch the bola.
> 
> Off-topic discussion will not be tolerated, make some actual criticisms rather than insulting the author of this PR.

OK VEGA, here's more actual criticism: You get rid of Ranger Takedown, then crushers made from blacksmithing and certain melee weapons from spawns become the next way to drop someone on the spot. Your narrative here is that "stun combat" suck, which is why I'm mentioning this.

The Ranger takedown according to the code is supposed to be a defensive move. 

You want to nerf it so bad, VEGA? It's intended to be a defensive move so if a Ranger changes their stance, why not make it reduce the user's movement while in takedown stance?

> > Sounds like this coder got ranger takedown'd and now wants it PR'd out of the game. Ever heard of right clicking yourself with help intent while in combat mode? It's surprisingly effective for being able to recuperate from a ranger takedown. Anybody can do it.
> 
> That isn't a solution to the issue.

It's one of few, but you don't consider it because you don't use right-click specialty functions. If this isn't a solution to the issue, then I can offer you another: shields, certain loadouts spawn with them. Shields exist on the map. They can block attacks and have the potential to prevent ranger takedowns.

> > Anybody can do it
> 
> Not everyone who plays this server is familiar with TG-style combat mechanics. A fair amount of our player base (myself included) doesn't even play with right-click speciality functionality on.

If I made an excuse like this or anyone else tried, the response would be: "skill issue, git gud, cope, seethe, and you're malding" If you mean to imply that a fair amount of players don't play with right-click specialty functions on, then what does that say about the majority of ranger players and most of which who get killed alone to Legionaries or other characters? What about the players who run into walls, but can't typically stand up just because they aren't familiar with right-click specialty functions?

> That aside - Ranger Takedown isn't something you'd normally run into while in a brawl. It's too powerful in it's current state to exist without any drawbacks whatsoever.

The Ranger Takedown not having any drawbacks isn't true. If you checked the code, you would see that there are two drawbacks. Let me list them for you.

Line 66
A.adjustStaminaLoss(30) //The disarm will cost stamina to use. You are able to take down four opponents in quick succession before your stamina caps out.

Line 69
D.DefaultCombatKnockdown(rand(10,30)) //Due to the defensive nature of the move, it shouldn't be longer than putting on a pair of cuffs. (30)

I know they aren't significant drawbacks but they are still drawbacks no matter what.

> > Imagine if a coder made a push to remove bolas just because "having your movement speed capped isn't generally fun" when you can just toggled throw on and catch the bola.
> 
> Context matters. Bola's function quite a bit different to an instant disarm/knockdown ability.
> 
> I suppose I should note that most players aren't insanely paranoid and do not have throw selected in the event someone _MIGHT_ bola them.

Bolas do function differently, but you have to stand in place to get the bola off of you. If you get hit by a ranger takedown or god forbid a legendary crusher (which you're taking a bunch of damage, probably getting stunned, and likely going to die anyway if it's the crusher) you're getting knocked down.

The Ranger Takedown can both be utilized offensively and defensively. Ranger Takedowns should be used for the sake of defense.

**Comment by BadAtThisGame302** [comment]
> > Sounds like this coder got ranger takedown'd and now wants it PR'd out of the game. Ever heard of right clicking yourself with help intent while in combat mode? It's surprisingly effective for being able to recuperate from a ranger takedown. Anybody can do it.
> 
> That isn't a solution to the issue.
> 
> > Anybody can do it
> 
> Not everyone who plays this server is familiar with TG-style combat mechanics. A fair amount of our player base (myself included) doesn't even play with right-click speciality functionality on.
> 
> That aside - Ranger Takedown isn't something you'd normally run into while in a brawl. It's too powerful in it's current state to exist without any drawbacks whatsoever.
> 
> > Imagine if a coder made a push to remove bolas just because "having your movement speed capped isn't generally fun" when you can just toggled throw on and catch the bola.
> 
> Context matters. Bola's function quite a bit different to an instant disarm/knockdown ability.
> 
> I suppose I should note that most players aren't insanely paranoid and do not have throw selected in the event someone _MIGHT_ bola them.

I don't understand, how is Ranger takedown "too powerful" is it its knockdown with no stun time or what? Because if that's the case then sleeping carp from TG (Berserker Rites the Vex gets) is as much if not more powerful than Ranger takedown.

**Comment by ErwinSnowden** [comment]
> OK VEGA, here's more actual criticism: You get rid of Ranger Takedown, then crushers made from blacksmithing and certain melee weapons from spawns become the next way to drop someone on the spot. *snip*

Crushers require effort to obtain, anyone can use them and they don't ignore the STUNIMMUNE trait... armor also applies?

It's like if we balanced the BoS on their potential power endround if they get their hands on G&B 5 and somehow have enough attachies to give everyone 50 damage AER9s.

Also if you don't know, the right click functionality literally does not work during the period that knockdown is applied, which is on average around 2 seconds? And it's not like old /tg/ knockdown where you automatically get up if moving because citadel thinks that "you should need to stand still to get up from knockdown." 

That 2+ seconds is enough for them to draw their sequoia and kill you instantly, during which you get zero recourse because you were forced to drop your gun and have to go through the draw time to shoot it.

**Comment by RonBag** [comment]
A flat removal of the takedown is not in the interest of game balance at this time.

**Pull request closed without merging**
