### PR TITLE
Revert "Circuits cannot be weaponised"

### PR DESCRIPTION
**Pull request by YellowKingThe**
Reverts AtomBombf13/AtomBomb#467

Revert the circuit changes, they were made by someone acting in bad faith who wants to just remove circuits as a whole and is going to keep chipping away at them until they don't exist.
If you actually want to fix circuits properly sit down with the people that use them identify the problems and work to fix them instead of just ripping things out.
Or if you really want to rip out features start replacing them with other things.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
The Circuit War of 2023

**Comment by ErwinSnowden** [comment]
This should not be reverted, before you could make a gatling laser out of AEP7s and power them off the grid using a large tesla relay. (or you can use the lifeweb meme circuit component that consumes blood for like 500000 kj per unit). 

contrary to your description of hangyul, you're acting in bad faith if you want shit like that in the game, or homing grenade primers, or pretty much anything else in the weaponized circuit tree.

**Comment by YellowKingThe** [comment]
Okay build a Gatling laser, and find enough AEP7s to make it run, and then keep the cells charged, weapon circuits still use the cell inside the gun, not the circuits energy.
The weapon circuit fires once every three seconds at most, and you can duck under them.
Also this has no effect on making explosive circuits beyond removing one trigger to make them, there are many other ways to make them.

**Comment by ErwinSnowden** [comment]
> Okay build a Gatling laser, and find enough AEP7s to make it run, and then keep the cells charged, weapon circuits still use the cell inside the gun, not the circuits energy. The weapon circuit fires once every three seconds at most, and you can duck under them. Also this has no effect on making explosive circuits beyond removing one trigger to make them, there are many other ways to make them.

You can use a power transmission circuit and logic to cycle through scanned power cells inside the circuit, AEP7s are super fucking common, the Brotherhood starts with 5 in a gun rack and the merchant can order them for the town for like 1500 cargo points for 2. With the bulky circuit shells, this is very easy to do since I've seen people make autonomous drones that power the internal cells of weapons.

**Comment by YellowKingThe** [comment]
Even heavy power transmission circuits take a long time to recharge an energy weapon cell, you are not going to be charging all of them off one unless it has a lot of down time.
Even if you stack like six it takes a long time to recharge something, you absolutely can not do continuous fire like a minigun with it lol.
The BoS starts with three in a rack, not sure where you got five.

**Comment by TheCircuitsClown** [comment]
> > Okay build a Gatling laser, and find enough AEP7s to make it run, and then keep the cells charged, weapon circuits still use the cell inside the gun, not the circuits energy. The weapon circuit fires once every three seconds at most, and you can duck under them. Also this has no effect on making explosive circuits beyond removing one trigger to make them, there are many other ways to make them.
> 
> You can use a power transmission circuit and logic to cycle through scanned power cells inside the circuit, AEP7s are super fucking common, the Brotherhood starts with 5 in a gun rack and the merchant can order them for the town for like 1500 cargo points for 2. With the bulky circuit shells, this is very easy to do since I've seen people make autonomous drones that power the internal cells of weapons.

Oh damn. Scaryyy shiiit maaan. You know, theres one guy that did these drones. Its me. I used bypass to make gatling laser from AEP7. O n l y me. Others simply dont know bypass as charging each cell will deplete drone battery in 3 seconds. And sadly, these badass drones never saw combat exept for EORG train and memes on wasteland.
Your comment would have a point if gatling laser circuits were common shit and used in combat.

**Comment by TheCircuitsClown** [comment]
> > 
> 
> Bypasses exist that allow people to recharge their cells almost instantly after a shot.

It was used in my cringe drones only, and still they are rare sight. I dont know whats your problem.

**Comment by TheCircuitsClown** [comment]
My scaaary circuit gatling drones are mainly for a show. They are manually controlled, they stay on same tile as me, they are unaccurate, but yes, high fire rate and big battery. You cannot kill a person with it, its simply impossible.

**Comment by TheCircuitsClown** [comment]
Common circuit players can make, only a simple plain turrets with 1 energy gun that shoots once in 3 seconds, and still this shit would need 2 more humongous generators with teslas and 1 transmission to charge that 1 gun 😂

**Comment by TheCircuitsClown** [comment]
You see bombers much more often than pew pew drones because weapon circuit is simply shit. You put a whole energy gun and if drone destroyed its GG, no refunds.
Making drone with tracker and a grenade is much better.

**Comment by TheCircuitsClown** [comment]
You know.. What circuits really DO NEED...
Is to fucking make drones counted as mobs instead of items, why you can carry them in hand, why can bullets fly abowe them, its bad. THIS is the reason why people like Hangyul are crying from Ji-Had bombers, they cant shoot them unless aimed at drone sprite.

**Comment by TheCircuitsClown** [comment]
You dont need a removal, you need fixes.

**Comment by BrotherHangyul** [comment]
my brother in christ atom bomb shut down :skull:

**Comment by Cartlord** [comment]
First, that doesn't make anything he said less valid. Second, why do you say it shut down? This isn't the first time it's just been down for a few days.

**Comment by BrotherHangyul** [comment]
> First, that doesn't make anything he said less valid. Second, why do you say it shut down? This isn't the first time it's just been down for a few days.

It's deleted permanently. Honto had a schizo fit.

**Comment by Cartlord** [comment]
Unless Honto's the only person willing to host the place, I don't see much issue - it's an open-source server, any asshole can download it & replace the server.

**Comment by BrotherHangyul** [comment]
> Unless Honto's the only person willing to host the place, I don't see much issue - it's an open-source server, any asshole can download it & replace the server.

This repo is not being actively maintained anymore, the new server will not return to AB code. Any PRs here will not be merged or reverted, for all intents and purposes, this codebase is dead. There is no point arguing further - any more comments, from here on, will not be responded to.

**Pull request closed without merging**
