### PR TITLE
Changes & Additions [PORT] [Ready 4 Reivew..?]

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Ports several PRs from the likes of  TG, Tau Ceti and Polaris.
Additions include:

- Welding EFX [#67725](https://github.com/tgstation/tgstation/pull/67725)
- Ballistics added to exosuits [#8480](https://github.com/PolarisSS13/Polaris/pull/8480) [Credit given for sound & proj sprites]
- Ports vehicle refactor from TG [#15558](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15558)
- Directional lights for exosuits [#61749](https://github.com/tgstation/tgstation/pull/61749)
- Exosuit armor modules now add (+) armor directly, rather then dividing the damage (so you can stack/specialize..)
- Combats can strafe, but can't move diagonally (it's silly, vehicles shouldn't move diagonally..) [Credit to TG]
- Combats are guaranteed to explode via vehicle explosion code. :) [Credit to TG]
- Rebalances some exosuits.
- Freedom Mechs [#394](https://github.com/sunset-wasteland/sunset-wasteland/pull/394)

Changes:
- Exosuit projectiles shouldn't runtime into the mech (uhh..)

Removals:
- Regrettably, removes NPC mecha_pilots as I couldn't figure out how to fix a linters bug the file was causing. If anyone knows how to fix - grab a mecha_pilot dm are available from your local citadel/TG/whatever branch.
- Removes the HONKER's snowflake mech abilities because of issues. It's now just a normal mech without everyone's favourite UI pasta.

Should be ready to review if there's a maintainer here. :)
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: See above.
imageadd: Welding EFX by Tau Ceti!
code: Ports the vehicle-mecha refactor by TG!
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
Annnd.. Done! Maybe. Would appreciate it if someone could enable the workflows, though?

**Comment by Lamasmaster** [comment]
Seems the comments broke somehow so you gotta fix that.

**Comment by githubuser4141** [comment]
> Seems the comments broke somehow so you gotta fix that.

uh-huh. Not too clear what the issue is/was but I added a newline.

**Comment by githubuser4141** [comment]
Can someone enable the workflows so I can see what's wrong, thanks.

**Comment by Stutternov** [comment]
Enabled workflows for you. 👍

**Comment by githubuser4141** [comment]
> Enabled workflows for you. 👍

Thanks! Should be good to review now.

**Pull request merged**
