### PR TITLE
Revert "Hobomat 2 electric boogaloo"

### PR DESCRIPTION
**Pull request by ErwinSnowden**
Reverts AtomBombf13/AtomBomb#357

Begins again, knowing when to let go.

### CODE REVIEW

**Comment by HanSolo1519** [comment]
absolutly fine with this, have a list of shit to fuck with balance/practicality wise. It's way too OP as it stands and it'd be shitty to keep it on the server while I fuck with cocking rng and movement speed crap.

Make it commenting out though, not deletion. It's OP and should be disabled pending a rework.

**Comment by ErwinSnowden** [comment]
i do not feel like reverting all that atm. someone can make an alternative PR or you can just revert this reversion and add in the new stats in a second commit.

**Comment by BadAtThisGame302** [comment]
> i do not feel like reverting all that atm. someone can make an alternative PR or you can just revert this reversion and add in the new stats in a second commit.

I will make a PR after this is merged that adds back a the other crafting recipes and some other things, but this can go if even the creator of the original PR agrees.

**Comment by HanSolo1519** [comment]
Yeah it's fine, I can finagle the files again. Same shit in the end.

**Comment by RonBag** [comment]
merge conflicts, but good otherwise

**Comment by ErwinSnowden** [comment]
I am evil thus I won't resolve the merge conflicts...

**Pull request merged**
