### PR TITLE
makes stimpaks + bitters harder to mass produce/obtain

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request
Before this change, there was never ever any point in using healing powder, you could obtain stimpaks either by doing two minutes of chemistry or buying them from a vendor for dirt-cheap. This changes that, penalizing everyone equally by doubling the stim and bitter recipes. You'll probably want to use poultices or powders whenever possible due to them being cheaper and easy to obtain as a result, though slower.

I've also removed the stimfluid recipe because it's insanely powergame-able with healmixes. Not only is it convenient, you can create oxatribicafluidpaks which outheal most sources of damage and aren't fun to play against, nor are they fun to balance. I believe you can still get stimfluid from extracting it from stimpaks but you can no longer mass produce it from a chemical dispenser, making powergamepaks harder to create.

Vendors have been adjusted, now you have to pay 75 for a stimpak or 200 for a super stimpak.

Trading points will buy stimpaks for 15 caps and super stimpaks for 40 caps.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
balance: Bitters and stimpaks take twice as much to create.
balance: The Medical Vendor's price has soared as stimpak scarcity becomes a problem due to losses in Baja.
/:cl:

### CODE REVIEW

**Comment by Al-1ce** [comment]
Painful truth of the situation. 75 is a lot though. Maybe 40-30 for regular stims and 60-50 for super.

**Comment by ErwinSnowden** [comment]
> Painful truth of the situation. 75 is a lot though. Maybe 40-30 for regular stims and 60-50 for super.

The point is making it so people pay other players for stimpaks or use improvised medicine, and not the vendors. The vendors should be something you use if you have no other option or if you're fine with burning money.

**Comment by ErwinSnowden** [comment]
> Will stims be made more valuable on selling to compensate?

Will do.

**Comment by Al-1ce** [comment]
> The point is making it so people pay other players for stimpaks or use improvised medicine, and not the vendors. The vendors should be something you use if you have no other option or if you're fine with burning money.

Fair enough.

**Comment by YellowKingThe** [comment]
This is a massive tribal/legion buff I frankly don't think they need.
All this will do is make factions the only ones able to get stims at all, which is a terrible way to balance things.
With very little effort from farming, you can get 100s of stim plants, even if you double their cost that is still more then you will ever use in a round.
Compound this with Legion and Tribals getting bonuses to healing rate from Powder/Bitters, it is just a bad idea all around and needs a lot more thought put into it for how it will effect the dynamic of the server.
Making stims harder to mass produce is not a bad idea but it can't just be stims it has to be all healing meds due to the aforementioned buff to healing rate, this will not fix the problem.

**Comment by ErwinSnowden** [comment]
> This is a massive tribal/legion buff I frankly don't think they need. All this will do is make factions the only ones able to get stims at all, which is a terrible way to balance things. With very little effort from farming, you can get 100s of stim plants, even if you double their cost that is still more then you will ever use in a round. Compound this with Legion and Tribals getting bonuses to healing rate from Powder/Bitters, it is just a bad idea all around and needs a lot more thought put into it for how it will effect the dynamic of the server. Making stims harder to mass produce is not a bad idea but it can't just be stims it has to be all healing meds due to the aforementioned buff to healing rate, this will not fix the problem.

"100s of stimplants" is a non-argument due to this requiring gene-engineering, something only the town can do without breaking the rules.

You should want to use healing powder over stims because they're cheap. Most wasters in the Mojave shouldn't be carrying stims, they should be using healing powder. Instead of making 500 bitters, the legion will now likely make 100 healing powder and 50 bitters... because the recipe isn't equal.

The "healing bonus" the legion get is a .5 difference as far as I'm aware, and that recently got nerfed in a PR by Ron. I already increased the bitter drink cost, though I can outright remove the buff that tribals get from healing powder if you'd like.

The point of this PR is to make people use healing powder more, much like how it was used on BD and CP, not buffing any faction.

**Comment by CaputCapital** [comment]
Because NCR being unable to produce medicine half of the time wasn't bad enough, now you go and make a PR like this. A character spending 200 caps for just a super stimpak sounds like a beginner's trap to me, because super stimpaks when injected slow you down considerably. It's not like you'll be able to out-heal the damage inflicted on you while under the effects of a super-stimpak.

Here's what you fail to account for:
While you want everybody to start using healing powder more, you fail to consider the fact that just about everyone except for Legion (and those with the correct trait if it's not broken) will suffer drawbacks from powder, poultice, and bitter drink.

**Comment by ErwinSnowden** [comment]
> Because NCR being unable to produce medicine half of the time wasn't bad enough. A character spending 200 caps for just a super stimpak sounds like a beginner's trap to me, because super stimpaks when injected slow you down considerably. It's not like you'll be able to out-heal the damage inflicted on you while under the effects of a super-stimpak.
> 
> Here's what you fail to account for: While you want everybody to start using healing powder more, you fail to consider the fact that just about everyone except for Legion (and those with the correct trait if it's not broken) will suffer drawbacks from powder, poultice, and bitter drink.

Everything here is demonstrably false and comes from the view of being a "light armor" player. Bitter drinks have no downside, even for non-legion. Legionnaires just get +0.5 healing from them. This isn't just an NCR nerf, it's a reduction in meds as a whole. Super stimpaks are quite good, they just don't align with your playstyle.

**Pull request closed without merging**
