### PR TITLE
Changes HP's DKS + Glock to the Gauss Pistol.

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request
This is comparable in power to his other loadouts [once the tribeam gets fixed] and more flavorful than "sniper rifle and best plasma pistol in the game." In terms of power, I don't think this skews balance. It's essentially a more powerful sequoia that shoots every 1.3 seconds (because of the sniper firerate nerf). Half as powerful as the old gauss rifle and without the glock, it shouldn't make the other loadouts obsolescent.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Gunslinger loadout to Head Paladin.
del: Heavy loadout from Head Paladin.
/:cl:

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
> can we just get a gauss rifle 😢

its legitimately too powerful as a scoped weapon to the point that its the only thing people would ever get.

**Review by RonBag — CHANGES_REQUESTED** [review]
The sprite for the magazine is invisible.

**Comment by ErwinSnowden** [comment]
I CAN'T TEST THIS!!! 😭

**Comment by ErwinSnowden** [comment]
Should be fixed now @RonBag

**Review by RonBag — APPROVED** [review]

**Pull request merged**
