### PR TITLE
Nerfs ESD ammo's stamina damage

### PR DESCRIPTION
**Pull request by RonBag**
## About The Pull Request
Nerfs 5mm ESD

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
https://github.com/AtomBombf13/AtomBomb/pull/439 What the dog doing?

**Comment by HanSolo1519** [comment]
Should mention that it nerfs the stamina damage, not the intended feature of being an emp gun (good change tho, they're not rubbers, they shouldn't act as them)

**Comment by ErwinSnowden** [comment]
No, they're fine as is with the current nerf.

**Comment by RonBag** [comment]
> No, they're fine as is with the current nerf.

Take your shitposting somewhere else, VEGA.

**Comment by RonBag** [comment]
> #439 What the dog doing?

That was an accidental buff.

**Pull request merged**
