### PR TITLE
rebalances brotherhood slots

### PR DESCRIPTION
**Pull request by ErwinSnowden**
## About The Pull Request
Some people were complaining about the BoS slots in discord and OOC on multiple occasions. Here's one example.
image

Comment on about any changes you think are unreasonable, I'll be happy to discuss alternative solutions.

I've reduced the Paladin caste's maximum count from 4 to 3, gave them trekking to compensate. Added an Elder slot, took away a Knight, Scribe and Initiate slot. Senior Knights and Knight-Captain lost their DKS recipe for a Wattz2k recipe since... mass produced snipers without clearing a bunker is bad. This evens out roles to have a balanced structure for the Chain that Binds.

Here's some rationale, let's look at NV. The explanation we have for not having an Elder is because our chapter isn't "full-strength." The Mojave Chapter has about 25 NPCs? 26 if you include Veronica? If you add the nameless knight scouts its maybe 30? The ironic thing about this is that our bunker actually has more senior personnel, the Mojave chapter only has one Senior Knight and Senior Scribe. We have two of each. Keep in mind, years after Helios. The one thing our bunker lacks as a balance measure is paladins, and they, unlike the paladins of the game, do not all use tribeams and gauss rifles.

Now, speech about New Vegas over. The various roles of the Brotherhood in-game start with crafting recipes for various weapons, energy or ballistics. This allows them to very easily mass produce M1 carbines, AER9s, DKSes, and lightweight plasma pistols.

You know what else they have? 22 slots before this PR's changes. The NCR only has about 25 slots, minus one for the representative since he's useless. Eight of those slots are just trooper roles. Three of them are medical roles. [This ignores off-duty slots because there aren't map-markers for them so they can't spawn in.] So that saying about them being "outnumbered 15-1" is just false? Even if you only count "combat roles" the Brotherhood has 10 and the NCR has maybe 20? That 2:1 max difference doesn't mean much when you can arm all your soldiers with snipers and build plastitanium defenses with conveyers, concrete and barbed wire.

So with the above said, I think that this change is actually a little too lenient, and if you don't believe so... please tell me why?

And if the argument is that the introduction of Elder as a role will cause problems, you can cause just as many problems, if not more as the Head Paladin currently? If people are being shitters with any role we ban them, we don't remove the role. That's not a code issue, it's a player issue. "Elder bad touch" in past servers was primarily done by admins, not players.

Keep in mind that Elder still has its 50 hour timelock so if someone plays Brotherhood that long without getting flagged as a shitter, I'd be surprised.

Also, should I do something about this? Renaming it to Head Knight seems... meh, but it is an east coast rank. Should we just pretend that it's totally a real thing?
image

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
balance: The Paladins have lost one of their own, but through their struggles learned the ancient art of desert trekking.
tweak: Scribes, Knights and Initiates were all docked by one slot. To make up for this, an Elder slot has been opened.
balance: Senior Knights and Knight-Captains lost knowledge on how to make DKS sniper rifles, they've focused on engineering Wattz2k's instead.
/:cl:

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
The support for the general idea of lowering paladins is pretty strong, for reference. (Taken from #bos-meeting-chat-nerds)
image
image
image
image

A few of them are saying to remove SP even, and just keep the normal 2 paladin slots. I'd encourage you to comment before downvoting considering there's clearly at least some support as to the idea of lessening paladins.

**Comment by BadAtThisGame302** [comment]
I see no reason as to why there's 2 paladin slots, it always was 1-1-1. Plus you should probably re-name the Head Knight back IMO.

**Comment by RonBag** [comment]
This needs to be coordinated with other BOS buffs and not done in conjunction. Otherwise the risk of over nerfing is very real and likely.

**Comment by ErwinSnowden** [comment]
> This needs to be coordinated with other BOS nerfs and not done at the same time. Otherwise the risk of over nerfing is very real and likely.

There aren't any other "BOS nerf" PRs open, the other ones open are bugfixes that actually serve to buff the production abilities of knights. 

Losing 3 slots is then trivial when you realize that knights will be able to craft every attachment at roundstart. 

It won't be possible to "overnerf" the Brotherhood unless we start challenging their robust logistics (roundstart mining equipment, R&D, hydroponics) or remove 40% of their slots. Changes like those won't be merged because it's content removal and not actually rebalancing.

If someone makes another Brotherhood rebalance PR, I'm fine to make any changes the maintainers want.

**Comment by RonBag** [comment]
> > This needs to be coordinated with other BOS nerfs and not done at the same time. Otherwise the risk of over nerfing is very real and likely.
> 
> There aren't any other "BOS nerf" PRs open, the other ones open are bugfixes that actually serve to buff the production abilities of knights.
> 
> Losing 3 slots is then trivial when you realize that knights will be able to craft every attachment at roundstart.
> 
> It won't be possible to "overnerf" the Brotherhood unless we start challenging their robust logistics (roundstart mining equipment, R&D, hydroponics) or remove 40% of their slots. Changes like those won't be merged because it's content removal and not actually rebalancing.
> 
> If someone makes another Brotherhood rebalance PR, I'm fine to make any changes the maintainers want.

PA nerf was just merged.

**Comment by ErwinSnowden** [comment]
PA's nerf was halved block chance and outside of the scope of this PR, in my opinion. Four paladin slots is still unreasonable for most people, even those who play in the Brotherhood. Common and OP Power Armor are two different issues that work together to destroy balance. 

They're a very defensive faction and ideally the change from 4>3 slots with trekking will allow them to defend strategic spots underground. Outside of highpop, all the paladin slots don't get filled, so this could actually be interpreted as a lowpop buff.

If the maintainers tell me to make changes, I will. The bottom line is that a large amount of people view the Brotherhood as being too powerful currently, and we need to change that somehow.

**Comment by RonBag** [comment]
> PA's nerf was halved block chance and outside of the scope of this PR, in my opinion. Four paladin slots is still unreasonable for most people, even those who play in the Brotherhood. Common and OP Power Armor are two different issues that work together to destroy balance.
> 
> They're a very defensive faction and ideally the change from 4>3 slots with trekking will allow them to defend strategic spots underground. Outside of highpop, all the paladin slots don't get filled, so this could actually be interpreted as a lowpop buff.
> 
> If the maintainers tell me to make changes, I will. The bottom line is that a large amount of people view the Brotherhood as being too powerful currently, and we need to change that somehow.

That's a nerf. The PA balance was a nerf and was merged already. I'm just suggesting give it time between each one to judge how it impacts the play. Or don't and merge them all at the same time and scratch heads in a couple of months why the faction is in the shitter.

**Comment by LOGANKELE2022** [comment]
This just seems like a salt pr from people mogging for a few rounds. BoS is not a TDM faction nor does it TDM. most of their numbers are from initiate-scribes and initiate-knight aspirants. These two roles have nothing in common and usually suck in terms of training, weapons and armor.

**Comment by YellowKingThe** [comment]
The thing about 25 NCR slots vs 22 BoS but then calling out the medical staff in NCR well not calling out the scribes is a bit disingenuous.
If we give them the same treatment you are looking at 24 NCR with 3 medical vs 22 BoS with I think around 6 if not more being Medical/Sci and not expected to fight.
Also people are going to play what they enjoy, if they can't there is a good chance they won't play.
The real outlier here is that Paladin armor is strong, Knights well a fighting caste are not really better off then other combat roles.

**Comment by ErwinSnowden** [comment]
> This just seems like a salt pr from people mogging for a few rounds. -snip-

Wrong, actually, most of the slots are knights which have 7 slots as a caste. I say knights and not knights/scribes because knights are the most active role in the Brotherhood. I don't know what kind of salt PR moderately changes a "non-TDM" faction to be more roleplay oriented by removing combat slots and adding to the chain of command.

Every knight gets combat armor, so do knight initiates. The only thing that "sucks" is their energy weapons which are on average worse than their ballistic counterparts, nothing is stopping you from giving them better weapons midround though. Ultimately, their training means nothing because this is a question of OOC balance.

**Comment by ErwinSnowden** [comment]
> Also people are going to play what they enjoy, if they can't there is a good chance they won't play. The real outlier here is that Paladin armor is strong, Knights well a fighting caste are not really better off then other combat roles.

If people aren't going to play because there isn't a Paladin slot open, maybe they should reconsider why they're playing the server? I'm sure everyone would like to play as the SS13 captain every round, but this isn't the case because other people get turns sometimes? You can always roleplay in a different faction or as a lesser rank for a round?

**Comment by ErwinSnowden** [comment]
Senior Knight lovers rejoice, all caste slots will be reduced by one equally now. DKS recipe is instead gone because I think it's problematic. A 10% reduction of faction slots isn't the end of the world, don't lose your minds over nothing.

**Comment by RonBag** [comment]
Unrelated to my above point, my only concern with the Elder role is what they would actually do in a round. Arbitration between castes when there is a dispute is made through the codex and I don't personally see how the role would be used in a constructive way. 

Technically, there is no "Elder office" on the map currently. They spawn in the codex room, and there is no spare offices. Seeing as the role is primarily an office role, I don't think it'd be appropriate to enable their spawning without adding a proper office.

**Comment by BadAtThisGame302** [comment]
The BoS is the only faction that has no central leader, there's 3 heads of 3 castes that are supposed to work together, which most times they don't.. the Elder might be needed to fix that problem, though I'm not exactly a BoS main so I don't know if the heads don't work together often.. but I have heard of a lot of that being the case.

**Comment by Legate-Maxson** [comment]
no playable elders.

**Pull request closed without merging**
